---

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install basic packages
  debug:
    msg: "{{ item }}"
  with_items:
    "{{ base__system_packages }}"

- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ base__system_packages }}"
