---

- name: Create interface dependency graph
  listen: reload interface config
  shell: "ifup -a --print-dependency=dot > /var/run/interfaces.dot"
  become: true

- name: Render interface dependency graph
  listen: reload interface config
  shell: "circo -Tsvg /var/run/interfaces.dot > /var/run/interfaces.svg"
  become: true

- name: Reload interface configuration
  listen: reload interface config
  shell: "ifreload -a"
  become: true
